---
# tasks file for faraday-agent
- name: "Update apt cache and install python3-pip"
  apt: 
    name:
      - python3-pip
    update_cache: true

- name: "Clone faraday-agent-dispatcher repository"
  git:
    repo: "https://github.com/infobyte/faraday_agent_dispatcher.git"
    dest: "{{ faraday_agent_dispatcher_repo_base_dir }}"
    clone: true

- name: "Install from source"
  pip:
    chdir: "{{ faraday_agent_dispatcher_repo_base_dir }}"
    state: "present"
    name: "."
    
